spring:
  application:
    name: task-manager

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task_manager}?useSSL=false
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:mysecretpassword}

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #JPA Settings
    hibernate:
      ddl-auto: update
