spring:
  application:
    name: task-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager?useSSL=false
    username: postgres
    password: mysecretpassword

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #JPA Settings
    hibernate:
      ddl_auto: update
